services:
  # elastic:
  #   image: elasticsearch:8.8.1
  #   container_name: elastic
  #   ports:
  #     - "9200:9200"
  #     - "9300:9300"
  #   networks:
  #     - elastic
  # kibana:
  #   image: kibana:8.8.1
  #   container_name: kibana
  #   ports: 
  #     - "5601:5601"
  #   depends_on: 
  #     - elastic
  #   networks: 
  #     - elastic
  # rabbitmq:
  #   image: rabbitmq:3.12.1
  #   container_name: rabbitmq
  #   ports:
  #     - "5672:5672"
  #   networks:
  #     - message-bus
  identity:
    image: identity-server
    container_name: identity-server
    build:
      context: CharacterSheet.IdentityService
      dockerfile: ./Dockerfile
    ports:
      - "5001:80"
    environment:
      - IDENTITY_BASE_URL=http://localhost:5001
      - IDENTITY_CALL_URL=http://host.docker.internal:5001
  gateway:
    image: gatewaty
    container_name: gateway
    build:
      context: CharacterSheet.Gateway
      dockerfile: ./Dockerfile
    ports:
      - "5002:80"
    environment:
      - IDENTITY_BASE_URL=http://localhost:5001