name: Restrict Merge to Main from Allowed Branches

on:
  pull_request:
    types:
      - opened
    branches:
      - main

env:
  ALLOWED_BRANCHES: '["development"]'

jobs:
  restrict_merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        run: |
          allowed_branches=${{ fromJSON(github.env.ALLOWED_BRANCHES) }}
          source_branch="${{ github.event.pull_request.head.ref }}"
          if [[ ! " ${allowed_branches[@]} " =~ " ${source_branch} " ]]; then
            echo "Pull requests to main must be opened from one of the allowed branches: ${ALLOWED_BRANCHES}"
            exit 1
          fi
